#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2016 F5 Networks
#      All rights reserved.
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will gather facts that 
#      are defined next to "include"

- name: Connecting...
  hosts: "{{bigip}}"
  connection: local

  tasks: 
   - name: Collect BIG-IP facts
     bigip_facts:
         server: "{{bigip}}"
         user: "admin"
         password: "admin"
         include: "interface"
         validate_certs: "no"
     delegate_to: localhost
